version: '3'
services:
  db:
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=store_dev
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/opt/store
    ports:
      - "8081:8081"
    environment:
      - "RAILS_ENV=development"
      - "DATABASE_HOST=db"
      - "DATABASE_USER=postgres"
    depends_on:
      - db
    command: "bundle exec rails server -b 0.0.0.0 -p 8081"
volumes:
  db:
    driver: local
networks:
  default:
    name: store-network
